name: Update Implementation

on:
  issues:
    types: [opened]

jobs:
  analyze-changes:
    runs-on: ubuntu-latest
    if: github.event.issue.title == 'OpenAI Agents SDK Update'
    steps:
      - uses: actions/checkout@v3

      - name: Analyze changes
        run: |
          # 変更内容を解析
          CHANGES=$(curl -s https://api.github.com/repos/openai/openai-agents-python/compare/$(cat .openai-agents-commit)...$(curl -s https://api.github.com/repos/openai/openai-agents-python/commits/main | jq -r .sha))

          # 変更の種類を分類
          FEATURES=$(echo $CHANGES | jq -r '.commits[].commit.message | select(contains("feat"))')
          FIXES=$(echo $CHANGES | jq -r '.commits[].commit.message | select(contains("fix"))')

          # 変更内容をコメントとして追加
          gh issue comment ${{ github.event.issue.number }} --body "### 変更内容の分析\n\n#### 新機能\n$FEATURES\n\n#### 修正\n$FIXES"
